# Generated by Django 6.0.2 on 2026-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('capacite', models.IntegerField()),
                ('localisation', models.CharField(choices=[('interieur', 'Intérieur'), ('terrasse', 'Terrasse'), ('salon_prive', 'Salon Privé')], default='interieur', max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
