# Generated by Django 6.0.4 on 2026-04-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('client_email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('CONFIRMATION', 'Confirmation'), ('ANNULATION', 'Annulation')], max_length=20)),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('ECHOUEE', 'Échouée')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
